name: CI testing html

on:
  workflow_call:
jobs:
  testing-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Listar archivos
        run: |
          ls -l
          cd aws-s3/web 
          ls
          
      - name: Checkout repository
        uses: actions/checkout@v2
              
      - name: Install dependencies
        run: npm install htmlhint -g
              
      - name: Validate HTML files
        run: htmlhint "**/*.html"
